### ISSUE TITLE
Error TikTok command

### ISSUE THREAD

**Issue by NikitoDev** [FantoX001/Miku-MD#38]
TypeError: MikuTiktok is not a function
    at Miku (C:\Users\User\Desktop\Bot\Core.js:3304:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot use 'in' operator to search for 'text' in TypeError: MikuTiktok is not a function
    at Miku (C:\Users\User\Desktop\Bot\Core.js:3304:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at generateWAMessageContent (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:205:16)
    at generateWAMessage (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:420:102)
    at Object.sendMessage (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:500:69)
    at Miku (C:\Users\User\Desktop\Bot\Core.js:5030:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) unhandledRejection
TypeError: Cannot read properties of undefined (reading 'match')
    at extractUrlFromText (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:40:67)
    at generateLinkPreviewIfRequired (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:44:48)
    at generateWAMessageContent (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:209:71)
    at generateWAMessage (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:420:102)
    at Object.sendMessage (C:\Users\User\Desktop\Bot\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:500:69)
    at reply (C:\Users\User\Desktop\Bot\Core.js:233:18)
    at Miku (C:\Users\User\Desktop\Bot\Core.js:3302:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) unhandledRejection

**Comment by FantoX001** [comment]
The module is broken. My exams are going on, I will fix it as soon as possible. 

Thank you.

**Comment by NikitoDev** [comment]
Thank you :D
